//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Programma_8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Режим сервера.
    /// </summary>
    // *** Start programmer edit section *** (РежимСервера CustomAttributes)

    // *** End programmer edit section *** (РежимСервера CustomAttributes)
    public enum РежимСервера
    {
        
        // *** Start programmer edit section *** (РежимСервера.Стабилизорованный CustomAttributes)

        // *** End programmer edit section *** (РежимСервера.Стабилизорованный CustomAttributes)
        [Caption("Стабилизорованный")]
        Стабилизорованный,
        
        // *** Start programmer edit section *** (РежимСервера.Отключенный CustomAttributes)

        // *** End programmer edit section *** (РежимСервера.Отключенный CustomAttributes)
        [Caption("Отключенный")]
        Отключенный,
        
        // *** Start programmer edit section *** (РежимСервера.Подключенный CustomAttributes)

        // *** End programmer edit section *** (РежимСервера.Подключенный CustomAttributes)
        [Caption("Подключенный")]
        Подключенный,
    }
}
